-- auto-generated definition
CREATE SCHEMA bookmarks COLLATE utf8mb4_general_ci;

CREATE DATABASE bookmark;
CREATE USER 'bookmark'@'localhost' IDENTIFIED BY 'put_pasword_here';
GRANT ALL ON bookmark.* to 'bookmark'@'192.168.1.153' IDENTIFIED BY 'put_pasword_here' WITH GRANT OPTION;
FLUSH PRIVILEGES;


GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE, GRANT OPTION ON bookmarks.* TO bookmarks@'192.168.%';
