-- auto-generated definition
CREATE SCHEMA bookmarks COLLATE utf8mb4_general_ci;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE, GRANT OPTION ON bookmarks.* TO bookmarks@'192.168.%';